version: '3.1'
services:
  mariadb:
    image: bitnami/mariadb:10.3
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: andre
      MARIADB_DATABASE: andre
    volumes:
      - maria_volume:/var/lib/mysql
volumes:
  maria_volume:
    driver: local